### ISSUE TITLE
通常行でも改行エスケープがしたい

### ISSUE THREAD

**Issue by vain0x** [vain0/hsp3_uedit#16]
プルリクへ移動: #37

**Comment by vain0** [comment]
ブランチ [wip_esc_newline](https://github.com/vain0/hsp3_uedit/tree/wip_esc_newline) にて仮実装がある。

2つ目の改行エスケープ以降の行番号が1大きくなってしまう、というバグがある。原因は調査中。

**Comment by vain0** [comment]
簡単なテスト。最初の assert の行を最初の行とする。
```hsp
	assert \
	__LINE__ == 1
	
	assert     \
	__LINE__   \
	== 4       \
	
	// \
	これはコメント
	
	onerror *LError
	mes 0/0

*LError
	assert lparam == 12
	end
```
