### ISSUE TITLE
配列拡張の高速化

### ISSUE THREAD

**Issue by vain0x** [vain0/hsp3_uedit#5]
プルリクエストへ移動: #34

**Comment by vain0** [comment]
簡易ベンチマークスクリプトを作成した: <https://gist.github.com/vain0/0d9cf5591bf5b27bb295>

**Comment by vain0** [comment]
現状: ブランチ [wip_speed](https://github.com/vain0/hsp3_uedit/tree/wip_stack) で作業中。(仮実装なのでデバッグは不十分。)
