### ISSUE TITLE
クローン変数の要素数とmasterが異常

### ISSUE THREAD

**Issue by vain0x** [vain0/hsp3_uedit#9]
## 問題1

struct 型の `dup` は要素数が異常になる。
### 原因

`dup` 命令は`HspVarProc::GetBlockSize` を要素数×nと解釈するが、これはstruct型については誤り。struct 型の HspVarProc の GetBlockSize は、prmstack バッファを見る。そのサイズは n \* sizeof(PVal)。
### 再現

``` hsp
#module kls x_
#global
  newmod v, kls
  dup w, v
  assert length(w) == 1 // 失敗する
  // w のデータをknowbugで見ようとすると、メモリアクセス違反で落ちることがある
```
## 問題2

`dup` によるクローン変数は、`PVal::master` が不定値になる。

`master` を使用する拡張型では、不正な挙動になりうる。(現実的にどうなるかは不明)
- なお `str` 型はクローン変数の場合には `master` を使わないので問題ない。
## 案
- `HspVarProc::Dup` メンバを追加し、`dup` 命令の実装を型ごとに定義させる。
  - #36

**Comment by vain0** [comment]
ブランチ [wip_ohsp_varproc_dup](https://github.com/vain0/hsp3_uedit/tree/wip_ohsp_varproc_dup) に仮実装がある。
